apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # Docker
  # local:
  #   push: false
  #  /Docker

  # Google cloud 
  googleCloudBuild:
    projectId: ticketings
  # /Google cloud 
  artifacts:
    # - image: ridmitri/auth
    - image: us.gcr.io/ticketings/auth    
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: ridmitri/tickets
    - image: us.gcr.io/ticketings/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: ridmitri/orders
    - image: us.gcr.io/ticketings/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: ridmitri/client-ticketing
    - image: us.gcr.io/ticketings/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
